/* 
 * File:   PeripheralSelect.h
 * Author: Ian
 *
 * Created on August 13, 2013, 5:48 PM
 */

#ifndef PERIPHERALSELECT_H
#define	PERIPHERALSELECT_H

#ifdef	__cplusplus
extern "C" {
#endif

#include "Common.h"
#include "Pins.h"

    /* ######## Peripheral Input Pin Select Module Mappings ######## */
#define INPUT_PPS_RB0 32
#define INPUT_PPS_RB1 33
#define INPUT_PPS_RB2 34
#define INPUT_PPS_RB3 35
#define INPUT_PPS_RB4 36
#define INPUT_PPS_RB5 37
#define INPUT_PPS_RB6 38
#define INPUT_PPS_RB7 39
#define INPUT_PPS_RB8 40
#define INPUT_PPS_RB9 41
#define INPUT_PPS_RB10 42
#define INPUT_PPS_RB11 43
#define INPUT_PPS_RB12 44
#define INPUT_PPS_RB13 45
#define INPUT_PPS_RB14 46
#define INPUT_PPS_RB15 47

#define INPUT_PPS_RC12 60
#define INPUT_PPS_RC13 61
#define INPUT_PPS_RC14 62

#define INPUT_PPS_RD0 64
#define INPUT_PPS_RD1 65
#define INPUT_PPS_RD2 66
#define INPUT_PPS_RD3 67
#define INPUT_PPS_RD4 68
#define INPUT_PPS_RD5 69
#define INPUT_PPS_RD6 70
#define INPUT_PPS_RD7 71
#define INPUT_PPS_RD8 72
#define INPUT_PPS_RD9 73
#define INPUT_PPS_RD10 74
#define INPUT_PPS_RD11 75

#define INPUT_PPS_RE0 80
#define INPUT_PPS_RE1 81
#define INPUT_PPS_RE2 82
#define INPUT_PPS_RE3 83
#define INPUT_PPS_RE4 84
#define INPUT_PPS_RE5 85
#define INPUT_PPS_RE6 86
#define INPUT_PPS_RE7 87

#define INPUT_PPS_RF0 96
#define INPUT_PPS_RF1 97
#define INPUT_PPS_RF2 98
#define INPUT_PPS_RF3 99
#define INPUT_PPS_RF4 100
#define INPUT_PPS_RF5 101
#define INPUT_PPS_RF6 102

#define INPUT_PPS_RG6 118
#define INPUT_PPS_RG7 119
#define INPUT_PPS_RG8 120
#define INPUT_PPS_RG9 121

        /* ######## Peripheral Output Pin Select Module Mappings ######## */
#define OUTPUT_PPS_RD0 _RP64R
#define OUTPUT_PPS_RD1 _RP65R
#define OUTPUT_PPS_RD2 _RP66R
#define OUTPUT_PPS_RD3 _RP67R
#define OUTPUT_PPS_RD4 _RP68R
#define OUTPUT_PPS_RD5 _RP69R
#define OUTPUT_PPS_RD6 _RP70R
#define OUTPUT_PPS_RD7 _RP71R

#define OUTPUT_PPS_RE0 _RP80R
#define OUTPUT_PPS_RE2 _RP82R
#define OUTPUT_PPS_RE4 _RP84R
#define OUTPUT_PPS_RE5 _RP85R
#define OUTPUT_PPS_RE7 _RP87R

#define OUTPUT_PPS_RF0 _RP96R
#define OUTPUT_PPS_RF1 _RP97R
#define OUTPUT_PPS_RF2 _RP98R
#define OUTPUT_PPS_RF3 _RP99R
#define OUTPUT_PPS_RF4 _RP100R
#define OUTPUT_PPS_RF5 _RP101R
#define OUTPUT_PPS_RF6 _RP102R

    /* ######## Mapping Concatenation ######## */
#define OUTPUT_MAP(port, num) _JOIN3(OUTPUT_PPS_R, port, num)
#define INPUT_MAP(port, num)  _JOIN3(INPUT_PPS_R, port, num)

    /* ######## Output Module Mapping ######## */
#define _OC1  0x10
#define _OC2  0x11
#define _OC3  0x12
#define _OC4  0x13
#define _OC5  0x14
#define _OC6  0x15
#define _OC7  0x16
#define _OC8  0x17
#define _OC9  0x25
#define _OC10 0x26
#define _OC11 0x27
#define _OC12 0x28
#define _OC13 0x29
#define _OC14 0x2A
#define _OC15 0x2B
#define _OC16 0x2C

    /* ######## Input Module Mapping ######## */
#define INT0
#define INT1 _INT1R
#define INT2 _INT2R
#define INT3 _INT3R
#define INT4 _INT4R

#define _IC1 _IC1R
#define _IC2 _IC2R
#define _IC3 _IC3R
#define _IC4 _IC4R
#define _IC5 _IC5R
#define _IC6 _IC6R
#define _IC7 _IC7R
#define _IC8 _IC8R
#define _IC9 _IC9R
#define _IC10 _IC10R
#define _IC11 _IC11R
#define _IC12 _IC12R
#define _IC13 _IC13R
#define _IC14 _IC14R
#define _IC15 _IC15R
#define _IC16 _IC16R

    /* ######## Bidirectional Module Mapping ######## */
#define SDO1 0x05
#define SCK1 0x06
#define SS1  0x07
#define SDI1 _SDI1R

#define SDO2 0x00
#define SCK2 0x00
#define SS2  0x00
#define SDI2

#define SDO3 0x1F
#define SCK3 0x20
#define SS3  0x21
#define SDI3 _SDI3R

#define SDO4 0x22
#define SCK4 0x23
#define SS4  0x24
#define SDI4 _SDI4R

    
    /* ####### DO NOT CHANGE.  The following maps user selections to code ####### */
#define MAP_PERIPHERAL_FLAG(module, num, IEorIF) _JOIN4(_, module, num, IEorIF)
#define MAP_PERIPHERAL_BITFIELD(module, num, reg) _JOIN4(module, num, reg, bits)
#define MAP_PERIPHERAL_REGISTER(module, num, reg) _JOIN3(module, num, reg)
#define MAP_PERIPHERAL_INTERRUPT(module, num)     _JOIN4(_, module, num, Interrupt)
#define MAP_PERIPHERAL_IP(module, num) _JOIN4(_, module, num, IP)

#define MAP_INT_BITFIELD(num, bitfield) _JOIN3(_INT, num, bitfield)

#define MAP_PPST(num) _JOIN2(DMAPPSbits.PPST, num)

#define MAP_INT_MODULE(num) _JOIN3(_INT, num, R)
#define MAP_IC_MODULE(num)  _JOIN3(_IC,  num, R)
#define MAP_OC_MODULE(num)  _JOIN2(_OC,  num)

#undef SPI
#undef IC
#undef OC

#define VMEAS_ADCON1 MAP_PERIPHERAL_BITFIELD(AD, VMEAS_ADC, CON1)
#define VMEAS_ADCON2 MAP_PERIPHERAL_BITFIELD(AD, VMEAS_ADC, CON2)
#define VMEAS_ADCON3 MAP_PERIPHERAL_BITFIELD(AD, VMEAS_ADC, CON3)
#define VMEAS_ADCON4 MAP_PERIPHERAL_BITFIELD(AD, VMEAS_ADC, CON4)
#define VMEAS_ADC_IE MAP_PERIPHERAL_FLAG(AD, VMEAS_ADC, IE)
#define VMEAS_ADC_IF MAP_PERIPHERAL_FLAG(AD, VMEAS_ADC, IF)
#define VMEAS_CSSL   MAP_PERIPHERAL_BITFIELD(AD, VMEAS_ADC, CSSL)

#define VMEAS_DMA_IE  MAP_PERIPHERAL_FLAG(DMA, VMEAS_DMA, IE)
#define VMEAS_DMA_IF  MAP_PERIPHERAL_FLAG(DMA, VMEAS_DMA, IF)
#define VMEAS_DMACON  MAP_PERIPHERAL_BITFIELD(DMA, VMEAS_DMA, CON)
#define VMEAS_DMAPAD  MAP_PERIPHERAL_REGISTER(DMA, VMEAS_DMA, PAD)
#define VMEAS_DMAREQ  MAP_PERIPHERAL_BITFIELD(DMA, VMEAS_DMA, REQ)
#define VMEAS_DMASTAL MAP_PERIPHERAL_REGISTER(DMA, VMEAS_DMA, STAL)
#define VMEAS_DMASTAH MAP_PERIPHERAL_REGISTER(DMA, VMEAS_DMA, STAH)
#define VMEAS_DMASTBL MAP_PERIPHERAL_REGISTER(DMA, VMEAS_DMA, STBL)
#define VMEAS_DMASTBH MAP_PERIPHERAL_REGISTER(DMA, VMEAS_DMA, STBH)
#define VMEAS_DMACNT  MAP_PERIPHERAL_REGISTER(DMA, VMEAS_DMA, CNT)
#define VMEAS_PPST    MAP_PPST(VMEAS_DMA)

#define VMEAS_TMR_IF MAP_PERIPHERAL_FLAG(T, VMEAS_TIMER, IF)
#define VMEAS_TMR_IE MAP_PERIPHERAL_FLAG(T, VMEAS_TIMER, IE)
#define VMEAS_TCONR  MAP_PERIPHERAL_REGISTER(T, VMEAS_TIMER, CON)
#define VMEAS_TCON   MAP_PERIPHERAL_BITFIELD(T, VMEAS_TIMER, CON)
#define VMEAS_PR     MAP_PERIPHERAL_REGISTER(PR, VMEAS_TIMER,)

#define LOOP_INTERRUPT MAP_PERIPHERAL_INTERRUPT(T, LOOP_TIMER)
#define LOOP_IF        MAP_PERIPHERAL_FLAG(T, LOOP_TIMER, IF)
#define LOOP_IE        MAP_PERIPHERAL_FLAG(T, LOOP_TIMER, IE)
#define LOOP_TCONR     MAP_PERIPHERAL_REGISTER(T, LOOP_TIMER, CON)
#define LOOP_TCON      MAP_PERIPHERAL_BITFIELD(T, LOOP_TIMER, CON)
#define LOOP_PR        MAP_PERIPHERAL_REGISTER(PR, LOOP_TIMER,)

#define ACC_DMA_INTERRUPT MAP_PERIPHERAL_INTERRUPT(DMA, ACC_DMA)
#define ACC_DMA_IE        MAP_PERIPHERAL_FLAG(DMA, ACC_DMA, IE)
#define ACC_DMA_IF        MAP_PERIPHERAL_FLAG(DMA, ACC_DMA, IF)
#define ACC_DMACON        MAP_PERIPHERAL_BITFIELD(DMA, ACC_DMA, CON)
#define ACC_DMAPAD        MAP_PERIPHERAL_REGISTER(DMA, ACC_DMA, PAD)
#define ACC_DMAREQ        MAP_PERIPHERAL_BITFIELD(DMA, ACC_DMA, REQ)
#define ACC_DMASTAL       MAP_PERIPHERAL_REGISTER(DMA, ACC_DMA, STAL)
#define ACC_DMASTAH       MAP_PERIPHERAL_REGISTER(DMA, ACC_DMA, STAH)
#define ACC_DMASTBL       MAP_PERIPHERAL_REGISTER(DMA, ACC_DMA, STBL)
#define ACC_DMASTBH       MAP_PERIPHERAL_REGISTER(DMA, ACC_DMA, STBH)
#define ACC_DMACNT        MAP_PERIPHERAL_REGISTER(DMA, ACC_DMA, CNT)
#define ACC_PPST          MAP_PPST(ACC_DMA)

#define ACC_INT_INTERRUPT MAP_PERIPHERAL_INTERRUPT(INT, ACC_INT)
#define ACC_INT_IE        MAP_PERIPHERAL_FLAG(INT, ACC_INT, IE)
#define ACC_INT_IF        MAP_PERIPHERAL_FLAG(INT, ACC_INT, IF)
#define ACC_INT_EP        MAP_INT_BITFIELD(ACC_INT, EP)
#define ACC_INT_MODULE    MAP_INT_MODULE(ACC_INT)

#define ACC_SPIBUF        MAP_PERIPHERAL_REGISTER(SPI, ACC_SPI, BUF)
#define ACC_SPI_IE        MAP_PERIPHERAL_FLAG(SPI, ACC_SPI, IE)
#define ACC_SPI_IF        MAP_PERIPHERAL_FLAG(SPI, ACC_SPI, IF)
#define ACC_SPI_CON1      MAP_PERIPHERAL_BITFIELD(SPI, ACC_SPI, CON1)
#define ACC_SPI_STAT      MAP_PERIPHERAL_BITFIELD(SPI, ACC_SPI, STAT)

#define GYRO_DMA_INTERRUPT MAP_PERIPHERAL_INTERRUPT(DMA, GYRO_DMA)
#define GYRO_DMA_IE        MAP_PERIPHERAL_FLAG(DMA, GYRO_DMA, IE)
#define GYRO_DMA_IF        MAP_PERIPHERAL_FLAG(DMA, GYRO_DMA, IF)
#define GYRO_DMACON        MAP_PERIPHERAL_BITFIELD(DMA, GYRO_DMA, CON)
#define GYRO_DMAPAD        MAP_PERIPHERAL_REGISTER(DMA, GYRO_DMA, PAD)
#define GYRO_DMAREQ        MAP_PERIPHERAL_BITFIELD(DMA, GYRO_DMA, REQ)
#define GYRO_DMASTAL       MAP_PERIPHERAL_REGISTER(DMA, GYRO_DMA, STAL)
#define GYRO_DMASTAH       MAP_PERIPHERAL_REGISTER(DMA, GYRO_DMA, STAH)
#define GYRO_DMASTBL       MAP_PERIPHERAL_REGISTER(DMA, GYRO_DMA, STBL)
#define GYRO_DMASTBH       MAP_PERIPHERAL_REGISTER(DMA, GYRO_DMA, STBH)
#define GYRO_DMACNT        MAP_PERIPHERAL_REGISTER(DMA, GYRO_DMA, CNT)
#define GYRO_PPST          MAP_PPST(GYRO_DMA)

#define GYRO_INT_INTERRUPT MAP_PERIPHERAL_INTERRUPT(INT, GYRO_INT)
#define GYRO_INT_IE        MAP_PERIPHERAL_FLAG(INT, GYRO_INT, IE)
#define GYRO_INT_IF        MAP_PERIPHERAL_FLAG(INT, GYRO_INT, IF)
#define GYRO_INT_EP        MAP_INT_BITFIELD(GYRO_INT, EP)
#define GYRO_INT_MODULE    MAP_INT_MODULE(GYRO_INT)

#define GYRO_SPIBUF        MAP_PERIPHERAL_REGISTER(SPI, GYRO_SPI, BUF)
#define GYRO_SPI_IE        MAP_PERIPHERAL_FLAG(SPI, GYRO_SPI, IE)
#define GYRO_SPI_IF        MAP_PERIPHERAL_FLAG(SPI, GYRO_SPI, IF)
#define GYRO_SPI_CON1      MAP_PERIPHERAL_BITFIELD(SPI, GYRO_SPI, CON1)
#define GYRO_SPI_STAT      MAP_PERIPHERAL_BITFIELD(SPI, GYRO_SPI, STAT)

#define THROTTLE_IC_INTERRUPT   MAP_PERIPHERAL_INTERRUPT(IC, THROTTLE_IC)
#define THROTTLE_IC_CON1        MAP_PERIPHERAL_BITFIELD(IC, THROTTLE_IC, CON1)
#define THROTTLE_IC_CON2        MAP_PERIPHERAL_BITFIELD(IC, THROTTLE_IC, CON2)
#define THROTTLE_IC_IE          MAP_PERIPHERAL_FLAG(IC, THROTTLE_IC, IE)
#define THROTTLE_IC_IF          MAP_PERIPHERAL_FLAG(IC, THROTTLE_IC, IF)
#define THROTTLE_ICBUF          MAP_PERIPHERAL_REGISTER(IC, THROTTLE_IC, BUF)
#define THROTTLE_IC_MODULE      MAP_IC_MODULE(THROTTLE_IC)

#define ROLL_IC_INTERRUPT   MAP_PERIPHERAL_INTERRUPT(IC, ROLL_TRIM_IC)
#define ROLL_IC_CON1        MAP_PERIPHERAL_BITFIELD(IC, ROLL_TRIM_IC, CON1)
#define ROLL_IC_CON2        MAP_PERIPHERAL_BITFIELD(IC, ROLL_TRIM_IC, CON2)
#define ROLL_IC_IE          MAP_PERIPHERAL_FLAG(IC, ROLL_TRIM_IC, IE)
#define ROLL_IC_IF          MAP_PERIPHERAL_FLAG(IC, ROLL_TRIM_IC, IF)
#define ROLL_ICBUF          MAP_PERIPHERAL_REGISTER(IC, ROLL_TRIM_IC, BUF)
#define ROLL_IC_MODULE      MAP_IC_MODULE(ROLL_TRIM_IC)

#define PITCH_IC_INTERRUPT   MAP_PERIPHERAL_INTERRUPT(IC, PITCH_TRIM_IC)
#define PITCH_IC_CON1        MAP_PERIPHERAL_BITFIELD(IC, PITCH_TRIM_IC, CON1)
#define PITCH_IC_CON2        MAP_PERIPHERAL_BITFIELD(IC, PITCH_TRIM_IC, CON2)
#define PITCH_IC_IE          MAP_PERIPHERAL_FLAG(IC, PITCH_TRIM_IC, IE)
#define PITCH_IC_IF          MAP_PERIPHERAL_FLAG(IC, PITCH_TRIM_IC, IF)
#define PITCH_ICBUF          MAP_PERIPHERAL_REGISTER(IC, PITCH_TRIM_IC, BUF)
#define PITCH_IC_MODULE      MAP_IC_MODULE(PITCH_TRIM_IC)

#define YAW_IC_INTERRUPT   MAP_PERIPHERAL_INTERRUPT(IC, YAW_TRIM_IC)
#define YAW_IC_CON1        MAP_PERIPHERAL_BITFIELD(IC, YAW_TRIM_IC, CON1)
#define YAW_IC_CON2        MAP_PERIPHERAL_BITFIELD(IC, YAW_TRIM_IC, CON2)
#define YAW_IC_IE          MAP_PERIPHERAL_FLAG(IC, YAW_TRIM_IC, IE)
#define YAW_IC_IF          MAP_PERIPHERAL_FLAG(IC, YAW_TRIM_IC, IF)
#define YAW_ICBUF          MAP_PERIPHERAL_REGISTER(IC, YAW_TRIM_IC, BUF)
#define YAW_IC_MODULE      MAP_IC_MODULE(YAW_TRIM_IC)

#define VSYNC_INT_INTERRUPT MAP_PERIPHERAL_INTERRUPT(INT, VSYNC_INT)
#define VSYNC_INT_IE        MAP_PERIPHERAL_FLAG(INT, VSYNC_INT, IE)
#define VSYNC_INT_IF        MAP_PERIPHERAL_FLAG(INT, VSYNC_INT, IF)
#define VSYNC_INT_EP        MAP_INT_BITFIELD(VSYNC_INT, EP)
#define VSYNC_INT_MODULE    MAP_INT_MODULE(VSYNC_INT)

#define PCLK_INT_INTERRUPT MAP_PERIPHERAL_INTERRUPT(INT, PCLK_INT)
#define PCLK_INT_IE        MAP_PERIPHERAL_FLAG(INT, PCLK_INT, IE)
#define PCLK_INT_IF        MAP_PERIPHERAL_FLAG(INT, PCLK_INT, IF)
#define PCLK_INT_EP        MAP_INT_BITFIELD(PCLK_INT, EP)
#define PCLK_INT_MODULE    MAP_INT_MODULE(PCLK_INT)

#define XVCLK_CON1R        MAP_PERIPHERAL_REGISTER(OC, XVCLK_OC, CON1)
#define XVCLK_CON2R        MAP_PERIPHERAL_REGISTER(OC, XVCLK_OC, CON2)
#define XVCLK_CON1         MAP_PERIPHERAL_BITFIELD(OC, XVCLK_OC, CON1)
#define XVCLK_CON2         MAP_PERIPHERAL_BITFIELD(OC, XVCLK_OC, CON2)
#define XVCLK_DUTY         MAP_PERIPHERAL_REGISTER(OC, XVCLK_OC, R)
#define XVCLK_PERIOD       MAP_PERIPHERAL_REGISTER(OC, XVCLK_OC, RS)
#define XVCLK_OC_MODULE    MAP_OC_MODULE(XVCLK_OC)

#define SHORT_HREF_TMR_IF      MAP_PERIPHERAL_FLAG(T, SHORT_HREF_TIMER, IF)
#define SHORT_HREF_TMR_IE      MAP_PERIPHERAL_FLAG(T, SHORT_HREF_TIMER, IE)
#define SHORT_HREF_TCONR       MAP_PERIPHERAL_REGISTER(T, SHORT_HREF_TIMER, CON)
#define SHORT_HREF_TCON        MAP_PERIPHERAL_BITFIELD(T, SHORT_HREF_TIMER, CON)
#define SHORT_HREF_PR          MAP_PERIPHERAL_REGISTER(PR, SHORT_HREF_TIMER,)
#define SHORT_HREF_TMR         MAP_PERIPHERAL_REGISTER(TMR, SHORT_HREF_TIMER,)

#define LONG_HREF_TMR_IF      MAP_PERIPHERAL_FLAG(T, LONG_HREF_TIMER, IF)
#define LONG_HREF_TMR_IE      MAP_PERIPHERAL_FLAG(T, LONG_HREF_TIMER, IE)
#define LONG_HREF_TCONR       MAP_PERIPHERAL_REGISTER(T, LONG_HREF_TIMER, CON)
#define LONG_HREF_TCON        MAP_PERIPHERAL_BITFIELD(T, LONG_HREF_TIMER, CON)
#define LONG_HREF_PR          MAP_PERIPHERAL_REGISTER(PR, LONG_HREF_TIMER,)
#define LONG_HREF_TMR         MAP_PERIPHERAL_REGISTER(TMR, LONG_HREF_TIMER,)
#define LONG_HREF_TMRHLD      MAP_PERIPHERAL_REGISTER(TMR, LONG_HREF_TIMER, HLD)

#define NRF_INT_INTERRUPT MAP_PERIPHERAL_INTERRUPT(INT, NRF_INT)
#define NRF_INT_IE        MAP_PERIPHERAL_FLAG(INT, NRF_INT, IE)
#define NRF_INT_IF        MAP_PERIPHERAL_FLAG(INT, NRF_INT, IF)
#define NRF_INT_EP        MAP_INT_BITFIELD(NRF_INT, EP)
#define NRF_INT_MODULE    MAP_INT_MODULE(NRF_INT)

#define NRF_DMA_INTERRUPT MAP_PERIPHERAL_INTERRUPT(DMA, NRF_DMA)
#define NRF_DMA_IE        MAP_PERIPHERAL_FLAG(DMA, NRF_DMA, IE)
#define NRF_DMA_IF        MAP_PERIPHERAL_FLAG(DMA, NRF_DMA, IF)
#define NRF_DMACON        MAP_PERIPHERAL_BITFIELD(DMA, NRF_DMA, CON)
#define NRF_DMAPAD        MAP_PERIPHERAL_REGISTER(DMA, NRF_DMA, PAD)
#define NRF_DMAREQ        MAP_PERIPHERAL_BITFIELD(DMA, NRF_DMA, REQ)
#define NRF_DMASTAL       MAP_PERIPHERAL_REGISTER(DMA, NRF_DMA, STAL)
#define NRF_DMASTAH       MAP_PERIPHERAL_REGISTER(DMA, NRF_DMA, STAH)
#define NRF_DMASTBL       MAP_PERIPHERAL_REGISTER(DMA, NRF_DMA, STBL)
#define NRF_DMASTBH       MAP_PERIPHERAL_REGISTER(DMA, NRF_DMA, STBH)
#define NRF_DMACNT        MAP_PERIPHERAL_REGISTER(DMA, NRF_DMA, CNT)
#define NRF_PPST          MAP_PPST(NRF_DMA)

#define NRF_DMA_BUF_INTERRUPT MAP_PERIPHERAL_INTERRUPT(DMA, NRF_DMA_BUF)
#define NRF_DMA_BUF_IE        MAP_PERIPHERAL_FLAG(DMA, NRF_DMA_BUF, IE)
#define NRF_DMA_BUF_IF        MAP_PERIPHERAL_FLAG(DMA, NRF_DMA_BUF, IF)
#define NRF_BUF_DMACON        MAP_PERIPHERAL_BITFIELD(DMA, NRF_DMA_BUF, CON)
#define NRF_BUF_DMAPAD        MAP_PERIPHERAL_REGISTER(DMA, NRF_DMA_BUF, PAD)
#define NRF_BUF_DMAREQ        MAP_PERIPHERAL_BITFIELD(DMA, NRF_DMA_BUF, REQ)
#define NRF_BUF_DMASTAL       MAP_PERIPHERAL_REGISTER(DMA, NRF_DMA_BUF, STAL)
#define NRF_BUF_DMASTAH       MAP_PERIPHERAL_REGISTER(DMA, NRF_DMA_BUF, STAH)
#define NRF_BUF_DMASTBL       MAP_PERIPHERAL_REGISTER(DMA, NRF_DMA_BUF, STBL)
#define NRF_BUF_DMASTBH       MAP_PERIPHERAL_REGISTER(DMA, NRF_DMA_BUF, STBH)
#define NRF_BUF_DMACNT        MAP_PERIPHERAL_REGISTER(DMA, NRF_DMA_BUF, CNT)
#define NRF_DMA_BUF_PPST      MAP_PPST(NRF_DMA_BUF)

#define NRF_SPIBUF        MAP_PERIPHERAL_REGISTER(SPI, NRF_SPI, BUF)
#define NRF_SPI_IE        MAP_PERIPHERAL_FLAG(SPI, NRF_SPI, IE)
#define NRF_SPI_IF        MAP_PERIPHERAL_FLAG(SPI, NRF_SPI, IF)
#define NRF_SPI_CON1      MAP_PERIPHERAL_BITFIELD(SPI, NRF_SPI, CON1)
#define NRF_SPI_STAT      MAP_PERIPHERAL_BITFIELD(SPI, NRF_SPI, STAT)

#define WR_DMA_TX_INTERRUPT MAP_PERIPHERAL_INTERRUPT(DMA, WR_DMA_TX)
#define WR_DMA_TX_IE        MAP_PERIPHERAL_FLAG(DMA, WR_DMA_TX, IE)
#define WR_DMA_TX_IF        MAP_PERIPHERAL_FLAG(DMA, WR_DMA_TX, IF)
#define WR_TX_DMACON        MAP_PERIPHERAL_BITFIELD(DMA, WR_DMA_TX, CON)
#define WR_TX_DMAPAD        MAP_PERIPHERAL_REGISTER(DMA, WR_DMA_TX, PAD)
#define WR_TX_DMAREQ        MAP_PERIPHERAL_BITFIELD(DMA, WR_DMA_TX, REQ)
#define WR_TX_DMASTAL       MAP_PERIPHERAL_REGISTER(DMA, WR_DMA_TX, STAL)
#define WR_TX_DMASTAH       MAP_PERIPHERAL_REGISTER(DMA, WR_DMA_TX, STAH)
#define WR_TX_DMASTBL       MAP_PERIPHERAL_REGISTER(DMA, WR_DMA_TX, STBL)
#define WR_TX_DMASTBH       MAP_PERIPHERAL_REGISTER(DMA, WR_DMA_TX, STBH)
#define WR_TX_DMACNT        MAP_PERIPHERAL_REGISTER(DMA, WR_DMA_TX, CNT)
#define WR_TX_PPST          MAP_PPST(WR_DMA_TX)

#define WR_DMA_RX_INTERRUPT MAP_PERIPHERAL_INTERRUPT(DMA, WR_DMA_RX)
#define WR_DMA_RX_IE        MAP_PERIPHERAL_FLAG(DMA, WR_DMA_RX, IE)
#define WR_DMA_RX_IF        MAP_PERIPHERAL_FLAG(DMA, WR_DMA_RX, IF)
#define WR_RX_DMACON        MAP_PERIPHERAL_BITFIELD(DMA, WR_DMA_RX, CON)
#define WR_RX_DMAPAD        MAP_PERIPHERAL_REGISTER(DMA, WR_DMA_RX, PAD)
#define WR_RX_DMAREQ        MAP_PERIPHERAL_BITFIELD(DMA, WR_DMA_RX, REQ)
#define WR_RX_DMASTAL       MAP_PERIPHERAL_REGISTER(DMA, WR_DMA_RX, STAL)
#define WR_RX_DMASTAH       MAP_PERIPHERAL_REGISTER(DMA, WR_DMA_RX, STAH)
#define WR_RX_DMASTBL       MAP_PERIPHERAL_REGISTER(DMA, WR_DMA_RX, STBL)
#define WR_RX_DMASTBH       MAP_PERIPHERAL_REGISTER(DMA, WR_DMA_RX, STBH)
#define WR_RX_DMACNT        MAP_PERIPHERAL_REGISTER(DMA, WR_DMA_RX, CNT)
#define WR_DMA_RX_PPST      MAP_PPST(WR_DMA_RX)

#define WR_SPI_INTERRUPT   MAP_PERIPHERAL_INTERRUPT(SPI, WR_SPI)
#define WR_SPIBUF          MAP_PERIPHERAL_REGISTER(SPI, WR_SPI, BUF)
#define WR_SPI_IE          MAP_PERIPHERAL_FLAG(SPI, WR_SPI, IE)
#define WR_SPI_IF          MAP_PERIPHERAL_FLAG(SPI, WR_SPI, IF)
#define WR_SPI_CON1        MAP_PERIPHERAL_BITFIELD(SPI, WR_SPI, CON1)
#define WR_SPI_STAT        MAP_PERIPHERAL_BITFIELD(SPI, WR_SPI, STAT)

#define FLAP_INTERRUPT MAP_PERIPHERAL_INTERRUPT(T, FLAP_TIMER)
#define FLAP_IF        MAP_PERIPHERAL_FLAG(T, FLAP_TIMER, IF)
#define FLAP_IE        MAP_PERIPHERAL_FLAG(T, FLAP_TIMER, IE)
#define FLAP_TCONR     MAP_PERIPHERAL_REGISTER(T, FLAP_TIMER, CON)
#define FLAP_TCON      MAP_PERIPHERAL_BITFIELD(T, FLAP_TIMER, CON)
#define FLAP_PR        MAP_PERIPHERAL_REGISTER(PR, FLAP_TIMER,)

#define VSYNC_IP       MAP_PERIPHERAL_IP(INT, VSYNC_INT)
#define PCLK_IP        MAP_PERIPHERAL_IP(INT, PCLK_INT)
#define NRF_DMA_IP     MAP_PERIPHERAL_IP(DMA, NRF_DMA)
#define WR_DMA_TX_IP   MAP_PERIPHERAL_IP(DMA, WR_DMA_TX)
#define WR_DMA_RX_IP   MAP_PERIPHERAL_IP(DMA, WR_DMA_RX)
#define NRF_INT_IP     MAP_PERIPHERAL_IP(INT, NRF_INT)
#define FLAP_TIMER_IP  MAP_PERIPHERAL_IP(T, FLAP_TIMER)
#define ACC_INT_IP     MAP_PERIPHERAL_IP(INT, ACC_INT)
#define ACC_DMA_IP     MAP_PERIPHERAL_IP(DMA, ACC_DMA)
#define GYRO_INT_IP    MAP_PERIPHERAL_IP(INT, GYRO_INT)
#define GYRO_DMA_IP    MAP_PERIPHERAL_IP(DMA, GYRO_DMA)
#define THROTTLE_IC_IP MAP_PERIPHERAL_IP(IC, THROTTLE_IC)
#define ROLL_IC_IP     MAP_PERIPHERAL_IP(IC, ROLL_TRIM_IC)
#define PITCH_IC_IP    MAP_PERIPHERAL_IP(IC, PITCH_TRIM_IC)
#define YAW_IC_IP      MAP_PERIPHERAL_IP(IC, YAW_TRIM_IC)
#define SHORT_HREF_IP  MAP_PERIPHERAL_IP(T, SHORT_HREF_TIMER)
#define LONG_HREF_IP   MAP_PERIPHERAL_IP(T, LONG_HREF_TIMER)
#define LOOP_TMR_IP    MAP_PERIPHERAL_IP(T, LOOP_TIMER)

    /* ######## Non-User Macros ######## */
#define MAP_OUTPUT_PORT_BIT_TO_RP_PIN(port, bit) _JOIN3(OUTPUT_PPS_R, port, bit)
#define MAP_INPUT_PORT_BIT_TO_RP_PIN(port, bit) _JOIN3(INPUT_PPS_R, port, bit)

#define ACC_SCK_RP  MAP_OUTPUT_PORT_BIT_TO_RP_PIN(ACC_CLK_PORT, ACC_CLK_BIT)
#define ACC_SDO_RP  MAP_OUTPUT_PORT_BIT_TO_RP_PIN(ACC_MOSI_PORT, ACC_MOSI_BIT)
#define ACC_SDI_RP  MAP_INPUT_PORT_BIT_TO_RP_PIN(ACC_MISO_PORT, ACC_MISO_BIT)
#define ACC_INT_RP  MAP_INPUT_PORT_BIT_TO_RP_PIN(ACC_INT1_PORT, ACC_INT1_BIT)

#define GYRO_SCK_RP  MAP_OUTPUT_PORT_BIT_TO_RP_PIN(GY_CLK_PORT, GY_CLK_BIT)
#define GYRO_SDO_RP  MAP_OUTPUT_PORT_BIT_TO_RP_PIN(GY_MOSI_PORT, GY_MOSI_BIT)
#define GYRO_SDI_RP  MAP_INPUT_PORT_BIT_TO_RP_PIN(GY_MISO_PORT, GY_MISO_BIT)
#define GYRO_INT_RP  MAP_INPUT_PORT_BIT_TO_RP_PIN(GY_DR_PORT, GY_DR_BIT)

#define THROTTLE_IC_RP MAP_INPUT_PORT_BIT_TO_RP_PIN(RC_IN4_PORT, RC_IN4_BIT)
#define ROLL_IC_RP     MAP_INPUT_PORT_BIT_TO_RP_PIN(RC_IN3_PORT, RC_IN3_BIT)
#define PITCH_IC_RP    MAP_INPUT_PORT_BIT_TO_RP_PIN(RC_IN2_PORT, RC_IN2_BIT)
#define YAW_IC_RP      MAP_INPUT_PORT_BIT_TO_RP_PIN(RC_IN1_PORT, RC_IN1_BIT)

#define NRF_INT_RP  MAP_INPUT_PORT_BIT_TO_RP_PIN(RF_INT_PORT, RF_INT_BIT)

#define WR_SS_RP    MAP_INPUT_PORT_BIT_TO_RP_PIN(WR_CS_PORT, WR_CS_BIT)

#define XVCLK_OC_RP MAP_OUTPUT_PORT_BIT_TO_RP_PIN(CAM_XVCLK_PORT, CAM_XVCLK_BIT)

#define VSYNC_INT_RP MAP_INPUT_PORT_BIT_TO_RP_PIN(CAM_VSYNC_PORT, CAM_VSYNC_BIT)
#define PCLK_INT_RP  MAP_INPUT_PORT_BIT_TO_RP_PIN(CAM_PCLK_PORT, CAM_PCLK_BIT)



#ifdef	__cplusplus
}
#endif

#endif	/* PERIPHERALSELECT_H */

